FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN apt update && apt install -y libgtk-3-0 libasound2 libx11-xcb1

WORKDIR /app

COPY . /app

RUN uv sync

EXPOSE 9987

CMD ["uv", "run", "app"]
